// KJY All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

namespace AGPGameplayTags
{
#pragma region [Input Tags]
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input);

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Native);										// Native 입력들(이동, 컨트롤러(카메라) 회전 등)
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Native_Move);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Native_Look);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Native_IngameMenu);

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability);									// Ability 입력들
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Active);								// Ability 활성화 입력
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Active_CombatMode);					// 전투 <-> 일반 모드 전환 입력
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Active_CombatMode_Enter);			// 전투모드 전환
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Active_CombatMode_Exit);				// 일반모드 전환
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Active_Attack);						// 공격스킬 입력
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Active_Attack_1);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Active_Attack_2);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Active_Special);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Active_Special_1);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Active_Special_2);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Active_Dodge);						// 회피 입력
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Active_Block);						// 방어 입력
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Active_TargetLock);					// 타겟잠금 입력
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Active_Rage);						// 분노 활성화 입력
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Active_ConsumeStone);					// 주위 Stone 사용 입력 키

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Event);								// 활성화된 Ability에 전달되는 Input Event
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Event_TargetLock);					// 타겟잠금 Ability내 전달되는 입력 이벤트
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Event_TargetLock_SwitchTarget);		// 타겟잠금 Ability내 전달되는 입력 이벤트(타겟전환)

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Lock);
#pragma endregion

#pragma region [Item Tags]
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Items);

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Items_Slots);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Items_Slots_Inventory);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Items_Slots_Equipment);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Items_Slots_Equipment_Weapons);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Items_Slots_Equipment_Weapons_Primary);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Items_Slots_Equipment_Weapons_Primary_1);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Items_Slots_Equipment_Weapons_Secondary);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Items_Slots_Equipment_Weapons_Secondary_1);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Items_Slots_Equipment_Cloths);

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Items_Types);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Items_Types_None);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Items_Types_Weapons);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Items_Types_Weapons_Axe);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Items_Types_Weapons_Sword);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Items_Types_Weapons_Club);
#pragma endregion

#pragma region [State]
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State);

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_CombatMode);								// 전투모드(무기들고있는상태 / 무기를집어넣은상태)
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_CombatMode_ON);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_CombatMode_OFF);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_CombatMode_Transition);					//전투 모드 전환중
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_CombatMode_Transition_Entering);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_CombatMode_Transition_Exiting);

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_DamageResponse);							// 피격 반응
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_DamageResponse_CrowdControl);			// 군중제어(HitReact, Stun 등)
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_DamageResponse_CrowdControl_HitReact);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_DamageResponse_Block);					// 방어
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_DamageResponse_Block_Success);			// 방어 성공
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_DamageResponse_Block_ParryReady);		// 패링(쳐내기) 가능
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_DamageResponse_Block_EnableCounter);		// 패링 후 카운터 공격 가능

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Rage);									// 분노
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Rage_Enter);								// 분노 상태 진입
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Rage_Activating);						// 분노 상태 활성화 중
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Rage_Exit);								// 분노 상태 종료

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Invincible);								// 무적

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Death);									// 사망

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_SpawnIntro);								// Spawn 직후 Intro 상태

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ActiveAbility);							// Ability 활성화중
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ActiveAbility_Attacking);				// Attacking Ability(Light, Heavy, Counter) 활성화중
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ActiveAbility_Attacking_Light);				
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ActiveAbility_Attacking_Heavy);				
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ActiveAbility_Attacking_Counter);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ActiveAbility_Special);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ActiveAbility_Special_Light);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ActiveAbility_Special_Heavy);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ActiveAbility_Dodge);					// 회피 Ability 활성화 중 
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ActiveAbility_Dodge_Roll);				
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ActiveAbility_Defending);				// 방어 Ability 활성화 중 
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ActiveAbility_Defending_Shield);		
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ActiveAbility_Summon);					// 소환 Ability 활성화 중
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ActiveAbility_Summon_SubMonster);

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Ability_Ongoing);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Ability_Ongoing_Summon);

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Interaction);							//캐릭터 - 다른 오브젝트들간의 상호작용 상태
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Interaction_Consume);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Interaction_Consume_Stone);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Interaction_ObjectActivate);

	/* 적용 보류.. 인벤토리 시스템 구축전까지 */
	//ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Interaction_Item);						// 상호작용 - 아이템
	//ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Interaction_Item_EquipItem);				// 상호작용 - 아이템 장착
	//ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Interaction_Item_DisrobeEquipment);		// 상호작용 - 아이템 장착 해제
#pragma endregion

#pragma region [Ability]
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability);

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Reactive);									// Active, Utility보다 우선순위
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Reactive_CrowdControl);					// CC기(HitReact, Stun 등)
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Reactive_CrowdControl_HitReact);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Reactive_Dead);							// 사망
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Reactive_Dead_ToDeath);					// 사망상태 진입
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Reactive_Dead_Destroy);					// 사망 이후 Destroy처리
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Reactive_Dead_Rebirth);					// 사망 => 부활 처리
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Reactive_Rage);							
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Reactive_Rage_Exit);						//분노 상태 종료
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Reactive_SpawnIntro);						//스폰 직후 Intro 상태

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_StateSwitch);								// 상태 전환 Ability
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_StateSwitch_CombatMode);					// CombatMode 전환
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_StateSwitch_CombatMode_Enter);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_StateSwitch_CombatMode_Exit);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_StateSwitch_Rage);							
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_StateSwitch_Rage_Enter);					// 분노 활성화

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Active);									// 캐릭터 활성화 스킬(공격, 버프 등)
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Active_Attack);							// 공격
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Active_Attack_Base);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Active_Attack_Base_Light);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Active_Attack_Base_Heavy);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Active_Special);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Active_Special_Light);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Active_Special_Heavy);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Active_Dodge);								// 회피
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Active_Dodge_Roll);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Active_Defense);							// 방어
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Active_Defense_Shield);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Active_Summon);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Active_Summon_SubMonster);
	
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ChainActive);								// Ability_Active에서 활성화될 수 있는 Ability
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ChainActive_BlockSuccess);					// 방어 활성화 도중 공격 방어 성공시 발동
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ChainActive_CounterAttack);				// 카운터 공격

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interaction);								//아이템, 기타 오브젝트등과의 상호작용 Ability
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interaction_Consume);						
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interaction_Consume_Stone);						// 주위 Stone Object 사용
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interaction_ObjectActivate);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interaction_Item);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interaction_Item_EquipItem);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interaction_Item_DisrobeEquipment);
	
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_PlayerControl);							// 플레이어 조작(타겟잠금 등) Ability
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_PlayerControl_TargetLock);
	
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Slot);										// Ability에 부여되는 Slot 정보
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Slot_Light);							
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Slot_Heavy);
#pragma endregion

#pragma region [Cooldown]
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown);

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Special);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Special_Light);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Special_Heavy);
#pragma endregion

#pragma region [GameplayEvents]
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event);

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Animation);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Animation_ComboInput);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Animation_ComboInput_Enable);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Animation_ComboInput_Disable);

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_CollisionHit);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_CollisionHit_Melee);

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Reaction);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Reaction_HitReact);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Reaction_SuccessBlock);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Reaction_Death);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Reaction_Death_Dying);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Reaction_Death_Death);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Reaction_Death_Destroy);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Reaction_Death_Rebirth);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Reaction_Death_None);

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Rage);							// 캐릭터 분노 상태 관련 이벤트
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Rage_ApplyGE);					// 캐릭터 분노 GE 적용
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Rage_Depleted);				// 분노 게이지 모두 감소 이벤트
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Rage_SpawnSlashProjectile);	// 분노상태에서 공격시 Slash 생성 이벤트

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Ability);						// Ability에서 사용하는 각종 이벤트들
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Ability_AOE);					// Ability - 범위내 타겟 탐지 및 데미지 적용
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Ability_Spawn);				
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Ability_Spawn_Projectile);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Ability_Spawn_SubMonster);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Ability_Spawn_Intro);

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Ability_Warning);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Ability_Warning_Unblockable);

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Ability_Dodge);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Ability_Dodge_Invincible);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Ability_Dodge_Invincible_Enter);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_Ability_Dodge_Invincible_Exit);
#pragma endregion

#pragma region [Animation]
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Animation);

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Animation_SetProperty);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Animation_SetProperty_AnimRefreshBone);
#pragma endregion

#pragma region [GameplayEffect]
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEffect);

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEffect_SetByCaller);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEffect_SetByCaller_ComboAttackCount);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEffect_SetByCaller_ComboAttackRate);
#pragma endregion

#pragma region [GameplayCue]
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_AttackType);

	/* 날카로운(Sharp) 공격 타입 : Sword, Axe 등*/
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_AttackType_Sharp);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_AttackType_Sharp_Axe);

	/* 둔기(Blunt) */
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_AttackType_Blunt);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_AttackType_Blunt_Club);

	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_HitType);
	ACTIONGAMEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_HitType_Organic);
#pragma endregion
}